import { createRoot } from "react-dom/client";
import App from "./App.tsx";
import "@fontsource/dancing-script/latin-400.css";
import "@fontsource/dancing-script/latin-700.css";
import "@fontsource/dancing-script/latin-ext-400.css";
import "@fontsource/dancing-script/latin-ext-700.css";
import "@fontsource/playfair-display/latin-400.css";
import "@fontsource/playfair-display/latin-700.css";
import "@fontsource/playfair-display/latin-400-italic.css";
import "@fontsource/playfair-display/latin-ext-400.css";
import "@fontsource/playfair-display/latin-ext-700.css";
import "@fontsource/playfair-display/latin-ext-400-italic.css";
import "@fontsource/lora/latin-400.css";
import "@fontsource/lora/latin-500.css";
import "@fontsource/lora/latin-400-italic.css";
import "@fontsource/lora/latin-ext-400.css";
import "@fontsource/lora/latin-ext-500.css";
import "@fontsource/lora/latin-ext-400-italic.css";
import "@fontsource/cormorant-garamond/latin-400.css";
import "@fontsource/cormorant-garamond/latin-500.css";
import "@fontsource/cormorant-garamond/latin-400-italic.css";
import "@fontsource/cormorant-garamond/latin-500-italic.css";
import "@fontsource/cormorant-garamond/latin-ext-400.css";
import "@fontsource/cormorant-garamond/latin-ext-500.css";
import "@fontsource/cormorant-garamond/latin-ext-400-italic.css";
import "@fontsource/cormorant-garamond/latin-ext-500-italic.css";
import "./index.css";

createRoot(document.getElementById("root")!).render(<App />);
